language: php
php:
  - '5.6'
  - '7.0'
  - nightly
install: ant generate-autoloader
script:
  - mkdir -p build/logs
  - ./build/tools/phpunit.phar --configuration ./build/phpunit.xml
after_success:
  - travis_retry php vendor/tools/coveralls.phar
